import test from "node:test";
import assert from "node:assert/strict";
import { openStore, postgresSchema, postgresSql } from "../../src/db/index.mjs";
import { createSharedState } from "../../src/runtime/shared-state.mjs";

test("SQLite rollback path remains usable through Bun", async () => {
  const store = openStore({ driver: "sqlite", uri: ":memory:" });
  await store.run("INSERT INTO projects (id, name, workspace_path, created_at) VALUES (?, ?, ?, ?)", [
    "P1", "rollback", "/tmp/rollback", 1,
  ]);
  assert.equal((await store.get("SELECT name FROM projects WHERE id = ?", ["P1"])).name, "rollback");
  await store.close();
});

test("PostgreSQL adapter rewrites positional parameters without touching quoted question marks", () => {
  assert.equal(postgresSql("SELECT '?' AS mark, id FROM tasks WHERE id = ? AND status = ?"),
    "SELECT '?' AS mark, id FROM tasks WHERE id = $1 AND status = $2");
  assert.match(postgresSql("INSERT OR IGNORE INTO execution_messages (execution_id, seq, role) VALUES (?, ?, ?)"),
    /ON CONFLICT \(execution_id, seq, role\) DO NOTHING$/);
});

test("generated PostgreSQL schema removes SQLite-only syntax", () => {
  const schema = postgresSchema();
  assert.doesNotMatch(schema, /PRAGMA|AUTOINCREMENT|SELECT RAISE/);
  assert.match(schema, /GENERATED BY DEFAULT AS IDENTITY/);
  assert.doesNotMatch(schema, /\bINTEGER\b/);
  assert.match(schema, /created_at\s+BIGINT NOT NULL/);
  assert.match(schema, /CREATE TABLE IF NOT EXISTS gateway_models/);
});

test("shared-state lock excludes a second instance", async () => {
  const state = await createSharedState();
  let nested = "not-run";
  await state.withLock("scheduler", 1_000, async () => {
    nested = await state.withLock("scheduler", 1_000, async () => "ran");
  });
  assert.equal(nested, null);
});
